# Project information
site_name: Selekt
site_url: https://bloomberg.github.io/selekt
repo_name: Selekt
repo_url: https://github.com/bloomberg/selekt
site_description: "A Kotlin and Android wrapper over SQLCipher, providing 256-bit AES encryption of database files"
site_author: Bloomberg L.P.
remote_branch: gh-pages
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Bloomberg L.P.

# Configuration
theme:
  name: material
  language: en
  palette:
    scheme: slate
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 'Overview': index.md
  - 'Getting started': getting_started.md
  - 'Native libraries': native_libraries.md
  - 'Benchmarks': benchmarks.md
  - 'API': kdoc/selekt-android/index.md
