module "selekt" {
  u                                          = local.all_users
  source                                     = "./standard-repo"
  name                                       = "selekt"
  description                                = "A Kotlin and Android wrapper over SQLCipher, providing 256-bit AES encryption of database files."
  private                                    = false
  topics                                     = ["sqlite", "sqlite3", "kotlin", "sqlcipher", "android"]
  url                                        = "https://bloomberg.github.io/selekt/"
  wiki                                       = false
  issues                                     = true
  has_downloads                              = false
  has_projects                               = true
  allow_merge_commit                         = true
  allow_squash_merge                         = false
  allow_rebase_merge                         = true
  delete_branch_on_merge                     = false
  vulnerability_alerts                       = true
  archived                                   = false
  maintainers                                = ["kshackleton1", "aabita"]
  maintainers_permission                     = "push"
  maintainers_team_name                      = "selekt-devs"
  admin_collaborators                        = []
  collaborators                              = []
  collaborator_permission                    = ""
  protected_branch                           = ["main"]
  enforce_admins                             = false
  require_reviews                            = false
  required_approving_review_count            = 1
  dismiss_stale_reviews                      = false
  dismissal_teams                            = []
  require_code_owner_reviews                 = false
  require_updated_branch                     = true
  require_DCO                                = true
  require_Coveralls                          = false
  require_TravisCI_PR                        = false
  require_TravisCI_CI                        = false
  require_ReadTheDocs                        = false
  required_Actions                           = [] 
}
