sonar.exclusions=\
  SQLite3/sqlite3/**,\
  SQLite3/src/main/external/**,\
  OpenSSL/build/**,\
  **/build/**,\
  **/generated/**

sonar.coverage.exclusions=\
  SQLite3/sqlite3/**,\
  SQLite3/src/main/external/**

sonar.cpd.exclusions=\
  SQLite3/sqlite3/**,\
  SQLite3/src/main/external/**
