build:
  maxIssues: 0

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true
  exclude:
    - 'XmlOutputReport'

comments:
  active: true
  excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
  CommentOverPrivateFunction:
    active: true
  CommentOverPrivateProperty:
    active: true
  UndocumentedPublicClass:
    active: false
    searchInInnerClass: true
    searchInInnerInterface: true
    searchInInnerObject: true
    searchInNestedClass: true
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  CognitiveComplexMethod:
    active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: true
    threshold: 11
  CyclomaticComplexMethod:
    active: true
    ignoreSimpleWhenEntries: true
  LabeledExpression:
    active: false
  LargeClass:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
  LongMethod:
    active: true
    threshold: 62 # TODO Adjust, ideally by reducing. Detekt was refactored for 1.0.0-RC13 to count lines of source code.
  LongParameterList:
    active: true
    ignoreDefaultParameters: false
    functionThreshold: 6
    constructorThreshold: 7
  MethodOverloading:
    active: true
    threshold: 6
  NestedBlockDepth:
    active: true
    threshold: 4
  ReplaceSafeCallChainWithRun:
    active: true
  StringLiteralDuplication:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
    excludeStringsWithLessThan5Characters: true
    ignoreAnnotation: true
    ignoreStringsRegex: '$^'
    threshold: 3
  TooManyFunctions:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
    ignoreOverridden: true
    ignorePrivate: true
    thresholdInClasses: 16
    thresholdInEnums: 11
    thresholdInFiles: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "^(_|(ignore).*)"
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames: ['equals','finalize','hashCode','toString']
  InstanceOfCheckForException:
    active: false
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: false
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - IndexOutOfBoundsException
      - NullPointerException
      - RuntimeException
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - Error
      - Exception
      - RuntimeException
      - Throwable
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][A-Za-z0-9]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z](_?[a-zA-Z0-9])*'
  ForbiddenClassName:
    active: true
    forbiddenName: []
  FunctionMaxLength:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
    maximumFunctionNameLength: 40
  FunctionMinLength:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
    minimumFunctionNameLength: 2
  FunctionNaming:
    active: false # DSL.
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
    functionPattern: '[a-z$][a-zA-Z$0-9]*'
  MatchingDeclarationName:
    active: true
  NoNameShadowing:
    active: true
  ObjectPropertyNaming:
    active: true
    constantPattern: '[A-Za-z](_?[A-Za-z0-9])*'
    propertyPattern: '[A-Za-z](_?[A-Za-z0-9])*'
    privatePropertyPattern: '[A-Za-z](_?[A-Za-z0-9])*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][a-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
  VariableMaxLength:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
    maximumVariableNameLength: 40
  VariableMinLength:
    active: false
    minimumVariableNameLength: 1
  VariableNaming:
    active: true
    excludeClassPattern: '$^'
    privateVariablePattern: '_?([a-z]||bU)([a-z0-9][a-zA-Z0-9]*)?'
    variablePattern: '([a-z]|bU)([a-z0-9][a-zA-Z0-9]*)?'

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: false # TODO Activate?
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  DoubleMutabilityForCollection:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: false
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullCheck:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  active: true
  AlsoCouldBeApply:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: false
  DataClassShouldBeImmutable:
    active: false
  EqualsNullCall:
    active: true
  ForbiddenComment:
    active: false
    values: ['TODO:','FIXME:','STOPSHIP:']
  ForbiddenImport:
    active: true
    imports: ['org.junit.Assert.assertTrue','org.junit.Assert.assertFalse','org.junit.Assert.assertNotNull','org.junit.Assert.assertNull']
  ForbiddenVoid:
    active: false
  MagicNumber:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
    ignoreAnnotation: false
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreHashCodeFunction: false
    ignoreNamedArgument: true
    ignoreNumbers: ['-1','0','1','2','443']
    ignorePropertyDeclaration: false
  MandatoryBracesIfStatements:
    active: true
  MaxLineLength:
    active: true
    excludes: ['**/integrationTest/**','**/jmh/**','**/test/**']
    excludeImportStatements: false
    excludePackageStatements: false
    excludeCommentStatements: true
    maxLineLength: 125
  MayBeConst:
    active: true
  NestedClassesVisibility:
    active: false
  ModifierOrder:
    active: true
  NewLineAtEndOfFile:
    active: true
  NoTabs:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalWhenBraces:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  ReturnCount:
    active: true
    max: 2
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    active: true
    max: 2
  TrailingWhitespace:
    active: true
  TrimMultilineRawString:
    active: true
  UnderscoresInNumericLiterals:
    active: true
    acceptableLength: 5
  UnnecessaryAbstractClass:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UnusedPrivateClass:
    active: false # TODO Activate me?
  UseDataClass:
    active: true
  UseSumOfInsteadOfFlatMapSize:
    active: true
  WildcardImport:
    active: true
