name: 'Periodic Integration Tests'

on:
  schedule:
    - cron: '0 22 * * SUN'

permissions: read-all

jobs:
  ci-pipeline:
    name: 'Continuous Integration'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: 'Install system packages'
        run: sudo apt-get install -y --no-install-recommends clang gcc make sed tcl
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: 'Integration tests'
        run: |
          ./gradlew integrationTest
