name: 'Publish Documentation'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  pipeline:
    name: 'GitHub Pages'
    runs-on: ubuntu-latest
    steps:
      - name: 'Set current year'
        run: echo "YEAR=$(date +'%Y')" >> $GITHUB_ENV
      - name: 'Install system packages'
        run: sudo apt-get install -y --no-install-recommends clang gcc make sed tcl
      - name: 'Install Build Tools'
        run: echo 'y' | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install 'build-tools;30.0.3'
      - name: 'Install CMake'
        run: echo 'y' | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install 'cmake;3.18.1'
      - name: 'Install NDK'
        run: echo 'y' | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install 'ndk;21.4.7075529'
      - name: 'Install Android SDK'
        run: echo 'y' | sudo ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager --install 'platforms;android-30'
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material
      - name: 'Configure local.properties'
        run: |
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
      - name: 'Dokka'
        run: |
          ./gradlew :AndroidLib:dokkaGfm :ApiLib:dokkaGfm
      - name: 'Set version'
        run: echo "VERSION=$(grep -hnr 'versionName' gradle.properties | sed 's/.*=//')" >> $GITHUB_ENV
      - name: 'Mkdocs'
        run: |
          git fetch origin gh-pages:gh-pages
          sed -i 's/<year>/${{ env.YEAR }}/g' docs/*.md
          sed -i 's/<year>/${{ env.YEAR }}/g' mkdocs.yml
          sed -i 's/<version>/${{ env.VERSION }}/g' docs/*.md
          mkdocs gh-deploy -m 'Automatic mkdocs deployment.'
