name: 'Publish Documentation'

on: [pull_request, push]

#on:
#  push:
#    branches:
#      - 'main'

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: 'Install Mkdocs'
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-material pymdown-extensions
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 'Generate KDocs'
        run: ./gradlew :AndroidLib:dokkaGfm :AndroidSupportLib:dokkaGfm :ApiLib:dokkaGfm
      - name: 'Populate Mkdocs fields'
        run: |
          VERSION=$(grep -hnr "versionName" gradle.properties | sed 's/.*=//')
          YEAR=$(date +'%Y')
          git fetch origin gh-pages:gh-pages
          sed -i 's/<version>/${VERSION}/g' docs/*.md
          sed -i 's/<year>/${YEAR}/g' mkdocs.yml
      - name: 'Deploy Mkdocs'
          mkdocs gh-deploy -r origin -t material -m 'Automatic mkdocs deployment.'
